# -*- coding: utf-8 -*-
"""ERG_Wavelet_PoC_Borisov.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mOxX5RHLbcL17miheyJB8WPriWIMZf4h
"""

# Imports: All available in Colab (numpy, pandas, scipy, matplotlib)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import find_peaks  # For peak detection
from scipy.ndimage import gaussian_filter1d  # For denoising

# Custom Ricker wavelet function (Mexican hat) - defined manually to avoid import issues
def ricker(points, a):
    """Return a Ricker wavelet (Mexican hat) - standard for ERG analysis."""
    vec = np.arange(-points // 2, points // 2 + 1, dtype=float)
    vec2 = (1 - vec**2 / (a**2 / 2)) * np.exp(-vec**2 / (a**2))
    return vec2 / np.abs(vec2).max()  # Normalized

print("Imports successful. Ready to load data.")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter1d

# Load Excel file
file_path = '/content/01 Appendix 1.xlsx'

try:
    # Read the sheet without specifying header, just load raw data
    df = pd.read_excel(file_path, sheet_name=0, header=None)

    # Find the row where "Time" is located (robust search)
    time_row_index = df[df.iloc[:, 0].astype(str).str.contains("Time", case=False, na=False)].index[0]

    # Load actual data starting from next row
    data = df.iloc[time_row_index + 1:, :2]  # Only first two columns (Time and Signal)

    # Convert to numeric, coerce errors to NaN
    t = pd.to_numeric(data.iloc[:, 0], errors='coerce').values
    signal = pd.to_numeric(data.iloc[:, 1], errors='coerce').values

    # Remove any rows with NaN (caused by headers, empty rows, or text)
    mask = ~np.isnan(t) & ~np.isnan(signal)
    t = t[mask]
    signal = signal[mask]

    print(f"Loaded ERG signal with {len(signal)} samples from Excel.")
    print("Sample data:", signal[:5])

except FileNotFoundError:
    print("File not found. Using synthetic fallback.")
    t = np.linspace(0, 0.5, 1000)  # Time in seconds
    signal = 50 * np.sin(2 * np.pi * 30 * t) * np.exp(-t / 0.1) + 10 * np.random.randn(len(t))

# Denoising with Gaussian filter
signal_denoised = gaussian_filter1d(signal, sigma=2)

# Plot Original vs Denoised
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(t, signal, label='Original ERG Signal')
plt.title('Original ERG Signal')
plt.xlabel('Time (ms)')
plt.ylabel('Voltage (µV)')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(t, signal_denoised, label='Denoised ERG Signal', color='green')
plt.title('Denoised ERG Signal (Gaussian Filter)')
plt.xlabel('Time (ms)')
plt.ylabel('Voltage (µV)')
plt.legend()

plt.tight_layout()
plt.show()

!pip install pandas openpyxl scipy matplotlib

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Load the Excel file (replace filename if needed)
file_path = '01 Appendix 1.xlsx'
xls = pd.ExcelFile(file_path)

# List all sheets to confirm
print(xls.sheet_names)

# Load a specific sheet (e.g., 'Oscillatory Potentials' – it has time-series data)
df = pd.read_excel(xls, sheet_name='Oscillatory Potentials', header=None)  # No header as data starts variably

# Display the first few rows to inspect
print(df.head(10))

import numpy as np
import pandas as pd

# Parameters
time_col = 0      # Column A: Time in ms
signal_col = 2    # CHANGE THIS: Try 2 for second signal, 3 for third, etc. (column 1 might be noisy or header-like)
data_guess_start = 6  # Rough start (around row 7 in Excel)

# Extract potential data block
potential_data = df.iloc[data_guess_start:, [time_col, signal_col]]

# Drop rows with any NaN or non-numeric in either column
potential_data = potential_data.apply(pd.to_numeric, errors='coerce')
potential_data = potential_data.dropna()

# Take from the block (assumes continuous numeric data after headers)
time = potential_data.iloc[:, 0].values.astype(float)
signal = potential_data.iloc[:, 1].values.astype(float)

print(f"Successfully extracted {len(time)} data points")
print("First 10 time values (ms):", time[:10])
print("First 10 signal values (µV):", signal[:10])

# Optional: Plot quick check
import matplotlib.pyplot as plt
plt.figure(figsize=(10,4))
plt.plot(time, signal)
plt.title(f'Extracted ERG Signal (Column {signal_col})')
plt.xlabel('Time (ms)')
plt.ylabel('Amplitude (µV)')
plt.show()

# Imports (already in your code; add find_peaks and cwt if needed)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter1d  # Denoising
from scipy.signal import find_peaks    # Peak detection
import scipy.signal as signal # Import the entire module to access cwt and ricker
import pywt # For Continuous Wavelet Transform

# Ensure pywt is installed
!pip install pywt

# Load data (your code)
file_path = '01 Appendix 1.xlsx'
xls = pd.ExcelFile(file_path)
df = pd.read_excel(xls, sheet_name='Oscillatory Potentials', header=None)

# Function to extract and analyze one signal column
def analyze_erg_signal(df, signal_col=2, sigma=2.0):
    time_col = 0
    data_guess_start = 6
    potential_data = df.iloc[data_guess_start:, [time_col, signal_col]]
    potential_data = potential_data.apply(pd.to_numeric, errors='coerce')
    potential_data = potential_data.dropna()

    time = potential_data.iloc[:, 0].values.astype(float)
    erg_signal = potential_data.iloc[:, 1].values.astype(float) # Renamed 'signal' to 'erg_signal'

    # Denoise
    denoised = gaussian_filter1d(erg_signal, sigma) # Use erg_signal

    # SNR estimate (refined: use mean signal power vs. noise std)
    noise = erg_signal - denoised # Use erg_signal
    snr = 20 * np.log10(np.mean(np.abs(erg_signal)) / np.std(noise) if np.std(noise) != 0 else np.inf) # Use erg_signal

    # Peak/Valley detection (for oscillatory potentials: adjust height/distance for ERG waves)
    peaks, _ = find_peaks(denoised, height=0.5, distance=5)  # Positive peaks (b-waves/oscillations)
    valleys, _ = find_peaks(-denoised, height=0.5, distance=5)  # Negative (a-waves)

    # Quantitative ERG metrics (example: avg amplitude, latency)
    if len(peaks) > 0 and len(valleys) > 0:
        avg_amp = np.mean(denoised[peaks] - denoised[valleys[:len(peaks)]])  # Peak-to-valley amps
        avg_latency = np.mean(time[peaks])  # Average implicit time
    else:
        avg_amp, avg_latency = 0, 0

    # CWT Scalogram (time-frequency: for detecting frequency-specific patterns) using pywt
    widths = np.arange(1, 31)  # Scales
    cwtmatr, freqs = pywt.cwt(denoised, widths, 'mexh') # Use pywt.cwt with 'mexh' (Mexican Hat) wavelet

    # Energy for pattern detection (high energy = potential abnormalities)
    energy = np.sum(np.abs(cwtmatr)**2, axis=0)
    threshold = np.percentile(energy, 95)
    pattern_indices = np.where(energy > threshold)[0]
    pattern_times = time[pattern_indices]

    # Print metrics
    print(f"Column {signal_col}: SNR = {snr:.2f} dB")
    print(f"Detected {len(peaks)} peaks (times ms): {time[peaks]}")
    print(f"Detected {len(valleys)} valleys (times ms): {time[valleys]}")
    print(f"Avg Oscillation Amplitude: {avg_amp:.2f} µV, Avg Latency: {avg_latency:.2f} ms")
    print(f"High-Energy Patterns at times (ms): {pattern_times}")

    # Plot
    fig, axs = plt.subplots(4, 1, figsize=(12, 16))
    axs[0].plot(time, erg_signal, label='Original') # Use erg_signal
    axs[0].plot(time, denoised, label='Denoised')
    axs[0].set_title(f'ERG Signal (Column {signal_col})')
    axs[0].set_xlabel('Time (ms)')
    axs[0].set_ylabel('Amplitude (µV)')
    axs[0].legend()

    axs[1].plot(time, denoised)
    axs[1].plot(time[peaks], denoised[peaks], 'x', label='Peaks')
    axs[1].plot(time[valleys], denoised[valleys], 'o', label='Valleys')
    axs[1].set_title('Peak/Valley Detection (Oscillatory Potentials)')
    axs[1].legend()

    axs[2].plot(time, energy)
    axs[2].scatter(time[pattern_indices], energy[pattern_indices], color='red')
    axs[2].set_title('Energy Across Scales (Pattern Detection)')

    axs[3].imshow(np.abs(cwtmatr), extent=[time.min(), time.max(), freqs.min(), freqs.max()], cmap='PRGn', aspect='auto')
    axs[3].set_title('Scalogram (CWT - Time-Frequency Analysis)')
    axs[3].set_ylabel('Scale (Higher = Lower Freq)')

    plt.tight_layout()
    plt.show()
    fig.savefig(f'erg_analysis_col{signal_col}.pdf')  # Save for application

# Analyze example column (try others like 3,4 for comparison)
analyze_erg_signal(df, signal_col=2)

# Optional: Loop over multiple columns (e.g., compare subjects)
# for col in [1,2,3,4]:  # Columns with signals
#     analyze_erg_signal(df, signal_col=col)